### PR TITLE
Issue#3 video model

### PR DESCRIPTION
**Pull request by Juanitaag1**
I am done with the Video Model.

### CODE REVIEW

**Review by jc-hayes — COMMENTED** [review]
Looks good, but I think there should also be a 'userId' property for the Video struct.

**Comment by Juanitaag1** [comment]
You are right James. I forgot to add the userId. Thanks.

**Comment by Juanitaag1** [comment]
Added userID to the Video model and also performed more unit testing.

**Review by jc-hayes — APPROVED** [review]
Looks good.

**Review by MeyAyre — APPROVED** [review]
Looks good from what I can tell

**Review by Bansenauer-Cascadia — COMMENTED** [review]
Looks good

**Review by Bansenauer-Cascadia — APPROVED** [review]

**Pull request merged**
